---
deployment:
  tasks:
    - export DEPLOYPATH=home/yco12mz50ka8/public_html
    - /bin/cp logo.html $DEPLOYPATH
    - /bin/cp home.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
