# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/yco12mz50ka8/public_html/
#     - /bin/cp -R ./ $DEPLOYPATH

  
---
deployment:
 tasks:
 - export DEPLOYPATH=/home/yco12mz50ka8/public_html/
 - /bin/cp logo.html $DEPLOYPATH
 - /bin/cp home.css $DEPLOYPATH